<?php
/**
 * ConfigurationObjectModulesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConfigurationObjectModulesTest Class Doc Comment
 *
 * @category    Class */
// * @description ConfigurationObjectModules
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationObjectModulesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConfigurationObjectModules"
     */
    public function testConfigurationObjectModules()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "schema_version"
     */
    public function testPropertySchemaVersion()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "configuration_id"
     */
    public function testPropertyConfigurationId()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "is_small_data"
     */
    public function testPropertyIsSmallData()
    {
    }

    /**
     * Test attribute "effective"
     */
    public function testPropertyEffective()
    {
    }

    /**
     * Test attribute "previous_data"
     */
    public function testPropertyPreviousData()
    {
    }

    /**
     * Test attribute "previous_created"
     */
    public function testPropertyPreviousCreated()
    {
    }

    /**
     * Test attribute "draft_data"
     */
    public function testPropertyDraftData()
    {
    }

    /**
     * Test attribute "draft_created"
     */
    public function testPropertyDraftCreated()
    {
    }

    /**
     * Test attribute "draft_comment"
     */
    public function testPropertyDraftComment()
    {
    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {
    }
}
