<?php
/**
 * EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueOverridesBgpTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueOverridesBgpTest Class Doc Comment
 *
 * @category    Class */
// * @description EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueOverridesBgp
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueOverridesBgpTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueOverridesBgp"
     */
    public function testEnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueOverridesBgp()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "asn"
     */
    public function testPropertyAsn()
    {
    }

    /**
     * Test attribute "neighbor_ip"
     */
    public function testPropertyNeighborIp()
    {
    }

    /**
     * Test attribute "neighbor_asn"
     */
    public function testPropertyNeighborAsn()
    {
    }

    /**
     * Test attribute "encryption"
     */
    public function testPropertyEncryption()
    {
    }
}
