<?php
/**
 * EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueTest Class Doc Comment
 *
 * @category    Class */
// * @description EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValue
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValue"
     */
    public function testEnterpriseinsertOrUpdateEnterpriseGatewayHandoffValue()
    {
    }

    /**
     * Test attribute "local_address"
     */
    public function testPropertyLocalAddress()
    {
    }

    /**
     * Test attribute "bgp"
     */
    public function testPropertyBgp()
    {
    }

    /**
     * Test attribute "overrides"
     */
    public function testPropertyOverrides()
    {
    }
}
