<?php
/**
 * EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueLocalAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueLocalAddressTest Class Doc Comment
 *
 * @category    Class */
// * @description EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueLocalAddress
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueLocalAddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueLocalAddress"
     */
    public function testEnterpriseinsertOrUpdateEnterpriseGatewayHandoffValueLocalAddress()
    {
    }

    /**
     * Test attribute "cidr_ip"
     */
    public function testPropertyCidrIp()
    {
    }

    /**
     * Test attribute "cidr_prefix"
     */
    public function testPropertyCidrPrefix()
    {
    }

    /**
     * Test attribute "use_for_private"
     */
    public function testPropertyUseForPrivate()
    {
    }

    /**
     * Test attribute "advertise_via_bgp"
     */
    public function testPropertyAdvertiseViaBgp()
    {
    }
}
