<?php
/**
 * ConfigurationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConfigurationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for configurationCloneConfiguration
     *
     * Clone a configuration.
     *
     */
    public function testConfigurationCloneConfiguration()
    {
    }

    /**
     * Test case for configurationCloneEnterpriseTemplate
     *
     * clone a new configuration.
     *
     */
    public function testConfigurationCloneEnterpriseTemplate()
    {
    }

    /**
     * Test case for configurationGetConfiguration
     *
     * Get a configuration profile.
     *
     */
    public function testConfigurationGetConfiguration()
    {
    }

    /**
     * Test case for configurationGetConfigurationModules
     *
     * .
     *
     */
    public function testConfigurationGetConfigurationModules()
    {
    }

    /**
     * Test case for configurationInsertConfigurationModule
     *
     * .
     *
     */
    public function testConfigurationInsertConfigurationModule()
    {
    }

    /**
     * Test case for configurationUpdateConfiguration
     *
     * .
     *
     */
    public function testConfigurationUpdateConfiguration()
    {
    }

    /**
     * Test case for configurationUpdateConfigurationModule
     *
     * .
     *
     */
    public function testConfigurationUpdateConfigurationModule()
    {
    }
}
