<?php
/**
 * EdgeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EdgeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EdgeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for edgeDeleteEdge
     *
     * .
     *
     */
    public function testEdgeDeleteEdge()
    {
    }

    /**
     * Test case for edgeEdgeCancelReactivation
     *
     * Cancel reactivation.
     *
     */
    public function testEdgeEdgeCancelReactivation()
    {
    }

    /**
     * Test case for edgeEdgeProvision
     *
     * Provision an edge.
     *
     */
    public function testEdgeEdgeProvision()
    {
    }

    /**
     * Test case for edgeEdgeRequestReactivation
     *
     * reactivate edge.
     *
     */
    public function testEdgeEdgeRequestReactivation()
    {
    }

    /**
     * Test case for edgeGetEdge
     *
     * Get edge info.
     *
     */
    public function testEdgeGetEdge()
    {
    }

    /**
     * Test case for edgeGetEdgeConfigurationStack
     *
     * .
     *
     */
    public function testEdgeGetEdgeConfigurationStack()
    {
    }

    /**
     * Test case for edgeSetEdgeHandOffGateways
     *
     * .
     *
     */
    public function testEdgeSetEdgeHandOffGateways()
    {
    }

    /**
     * Test case for edgeUpdateEdgeAdminPassword
     *
     * update credentials.
     *
     */
    public function testEdgeUpdateEdgeAdminPassword()
    {
    }

    /**
     * Test case for edgeUpdateEdgeAttributes
     *
     * Update edge attributes (name and description)..
     *
     */
    public function testEdgeUpdateEdgeAttributes()
    {
    }
}
