<?php
/**
 * EnterpriseApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EnterpriseApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for edgeDeleteEdgeRecords
     *
     * Deletes Edge record(s).
     *
     */
    public function testEdgeDeleteEdgeRecords()
    {
    }

    /**
     * Test case for enterpriseDeleteEnterprise
     *
     * Deletes enterprise.
     *
     */
    public function testEnterpriseDeleteEnterprise()
    {
    }

    /**
     * Test case for enterpriseDeleteEnterpriseGatewayRecords
     *
     * Deletes enterprise gateway record(s).
     *
     */
    public function testEnterpriseDeleteEnterpriseGatewayRecords()
    {
    }

    /**
     * Test case for enterpriseGetEnterpiseRouteConfiguration
     *
     * Get route advertisement and routing preferences policy.
     *
     */
    public function testEnterpriseGetEnterpiseRouteConfiguration()
    {
    }

    /**
     * Test case for enterpriseGetEnterpriseConfigurations
     *
     * get enterprise configuration profiles.
     *
     */
    public function testEnterpriseGetEnterpriseConfigurations()
    {
    }

    /**
     * Test case for enterpriseGetEnterpriseEdges
     *
     * Get edge list..
     *
     */
    public function testEnterpriseGetEnterpriseEdges()
    {
    }

    /**
     * Test case for enterpriseGetEnterpriseRouteTable
     *
     * .
     *
     */
    public function testEnterpriseGetEnterpriseRouteTable()
    {
    }

    /**
     * Test case for enterpriseGetEnterpriseServices
     *
     * .
     *
     */
    public function testEnterpriseGetEnterpriseServices()
    {
    }

    /**
     * Test case for enterpriseInsertEnterpriseNetworkAllocation
     *
     * insert enterprise network allocation.
     *
     */
    public function testEnterpriseInsertEnterpriseNetworkAllocation()
    {
    }

    /**
     * Test case for enterpriseInsertEnterpriseService
     *
     * Insert an enterprise service.
     *
     */
    public function testEnterpriseInsertEnterpriseService()
    {
    }

    /**
     * Test case for enterpriseInsertOrUpdateEnterpriseCapability
     *
     * .
     *
     */
    public function testEnterpriseInsertOrUpdateEnterpriseCapability()
    {
    }

    /**
     * Test case for enterpriseInsertOrUpdateEnterpriseGatewayHandoff
     *
     * .
     *
     */
    public function testEnterpriseInsertOrUpdateEnterpriseGatewayHandoff()
    {
    }

    /**
     * Test case for enterpriseUpdateEnterpriseNetworkAllocation
     *
     * .
     *
     */
    public function testEnterpriseUpdateEnterpriseNetworkAllocation()
    {
    }

    /**
     * Test case for enterpriseUpdateEnterpriseRoute
     *
     * .
     *
     */
    public function testEnterpriseUpdateEnterpriseRoute()
    {
    }

    /**
     * Test case for enterpriseUpdateEnterpriseRouteConfiguration
     *
     * .
     *
     */
    public function testEnterpriseUpdateEnterpriseRouteConfiguration()
    {
    }

    /**
     * Test case for enterpriseUpdateEnterpriseSecurityPolicy
     *
     * .
     *
     */
    public function testEnterpriseUpdateEnterpriseSecurityPolicy()
    {
    }

    /**
     * Test case for enterpriseUpdateEnterpriseService
     *
     * .
     *
     */
    public function testEnterpriseUpdateEnterpriseService()
    {
    }
}
