<?php
/**
 * MonitoringApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MonitoringApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MonitoringApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for monitoringGetAggregateEnterpriseEvents
     *
     * Fetch all ent. events.
     *
     */
    public function testMonitoringGetAggregateEnterpriseEvents()
    {
    }

    /**
     * Test case for monitoringGetAggregates
     *
     * Generate aggregate enterprise/edge information.
     *
     */
    public function testMonitoringGetAggregates()
    {
    }

    /**
     * Test case for monitoringGetEdgeBgpPeerStatus
     *
     * get BGP adjacency status for an edge.
     *
     */
    public function testMonitoringGetEdgeBgpPeerStatus()
    {
    }

    /**
     * Test case for monitoringGetEnterpriseBgpPeerStatus
     *
     * get enterprise BGP adjacency status.
     *
     */
    public function testMonitoringGetEnterpriseBgpPeerStatus()
    {
    }

    /**
     * Test case for monitoringGetEnterpriseEdgeLinkStatus
     *
     * edge and link status for monitoring.
     *
     */
    public function testMonitoringGetEnterpriseEdgeLinkStatus()
    {
    }
}
