<?php
/**
 * NetworkApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * NetworkApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NetworkApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for networkDeleteNetworkGatewayPool
     *
     * .
     *
     */
    public function testNetworkDeleteNetworkGatewayPool()
    {
    }

    /**
     * Test case for networkGetNetworkConfigurations
     *
     * Get configuration profiles.
     *
     */
    public function testNetworkGetNetworkConfigurations()
    {
    }

    /**
     * Test case for networkGetNetworkEnterprises
     *
     * Get list of enterprises by network..
     *
     */
    public function testNetworkGetNetworkEnterprises()
    {
    }

    /**
     * Test case for networkGetNetworkGatewayPools
     *
     * Get list of gateway pools.
     *
     */
    public function testNetworkGetNetworkGatewayPools()
    {
    }

    /**
     * Test case for networkGetNetworkGateways
     *
     * .
     *
     */
    public function testNetworkGetNetworkGateways()
    {
    }

    /**
     * Test case for networkGetNetworkOperatorUsers
     *
     * Get list of operator users associated with a network.
     *
     */
    public function testNetworkGetNetworkOperatorUsers()
    {
    }

    /**
     * Test case for networkInsertNetworkGatewayPool
     *
     * Insert gateway pool.
     *
     */
    public function testNetworkInsertNetworkGatewayPool()
    {
    }

    /**
     * Test case for networkUpdateNetworkGatewayPoolAttributes
     *
     * .
     *
     */
    public function testNetworkUpdateNetworkGatewayPoolAttributes()
    {
    }
}
