<?php
/**
 * UserMaintainanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserMaintainanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserMaintainanceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for enterpriseGetEnterpriseUsers
     *
     * Get list of enterprise users by enterprise id..
     *
     */
    public function testEnterpriseGetEnterpriseUsers()
    {
    }

    /**
     * Test case for enterpriseInsertEnterprise
     *
     * Insert an enterprise, owned by the operator or an MSP..
     *
     */
    public function testEnterpriseInsertEnterprise()
    {
    }

    /**
     * Test case for enterpriseInsertEnterpriseUser
     *
     * Insert an enterprise user.
     *
     */
    public function testEnterpriseInsertEnterpriseUser()
    {
    }

    /**
     * Test case for enterpriseUserDeleteEnterpriseUser
     *
     * Delete an enterprise user..
     *
     */
    public function testEnterpriseUserDeleteEnterpriseUser()
    {
    }

    /**
     * Test case for enterpriseUserUpdateEnterpriseUser
     *
     * Update an enterprise user.
     *
     */
    public function testEnterpriseUserUpdateEnterpriseUser()
    {
    }

    /**
     * Test case for operatorUserDeleteOperatorUser
     *
     * Delete an operator user.
     *
     */
    public function testOperatorUserDeleteOperatorUser()
    {
    }

    /**
     * Test case for operatorUserInsertOperatorUser
     *
     * Insert an operator user.
     *
     */
    public function testOperatorUserInsertOperatorUser()
    {
    }

    /**
     * Test case for operatorUserUpdateOperatorUser
     *
     * Update an operator user.
     *
     */
    public function testOperatorUserUpdateOperatorUser()
    {
    }
}
