<?php
/**
 * ConfigurationObjectModules
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Velocloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ConfigurationObjectModules Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationObjectModules implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'configuration_object_modules';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'created' => 'string',
        'name' => 'string',
        'type' => 'string',
        'description' => 'string',
        'schema_version' => 'string',
        'version' => 'string',
        'configuration_id' => 'int',
        'data' => 'object',
        'is_small_data' => 'int',
        'effective' => 'string',
        'previous_data' => 'string',
        'previous_created' => 'string',
        'draft_data' => 'object',
        'draft_created' => 'string',
        'draft_comment' => 'string',
        'modified' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'created' => null,
        'name' => null,
        'type' => null,
        'description' => null,
        'schema_version' => null,
        'version' => null,
        'configuration_id' => null,
        'data' => null,
        'is_small_data' => null,
        'effective' => null,
        'previous_data' => null,
        'previous_created' => null,
        'draft_data' => null,
        'draft_created' => null,
        'draft_comment' => null,
        'modified' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'created' => 'created',
        'name' => 'name',
        'type' => 'type',
        'description' => 'description',
        'schema_version' => 'schemaVersion',
        'version' => 'version',
        'configuration_id' => 'configurationId',
        'data' => 'data',
        'is_small_data' => 'isSmallData',
        'effective' => 'effective',
        'previous_data' => 'previousData',
        'previous_created' => 'previousCreated',
        'draft_data' => 'draftData',
        'draft_created' => 'draftCreated',
        'draft_comment' => 'draftComment',
        'modified' => 'modified'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'created' => 'setCreated',
        'name' => 'setName',
        'type' => 'setType',
        'description' => 'setDescription',
        'schema_version' => 'setSchemaVersion',
        'version' => 'setVersion',
        'configuration_id' => 'setConfigurationId',
        'data' => 'setData',
        'is_small_data' => 'setIsSmallData',
        'effective' => 'setEffective',
        'previous_data' => 'setPreviousData',
        'previous_created' => 'setPreviousCreated',
        'draft_data' => 'setDraftData',
        'draft_created' => 'setDraftCreated',
        'draft_comment' => 'setDraftComment',
        'modified' => 'setModified'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'created' => 'getCreated',
        'name' => 'getName',
        'type' => 'getType',
        'description' => 'getDescription',
        'schema_version' => 'getSchemaVersion',
        'version' => 'getVersion',
        'configuration_id' => 'getConfigurationId',
        'data' => 'getData',
        'is_small_data' => 'getIsSmallData',
        'effective' => 'getEffective',
        'previous_data' => 'getPreviousData',
        'previous_created' => 'getPreviousCreated',
        'draft_data' => 'getDraftData',
        'draft_created' => 'getDraftCreated',
        'draft_comment' => 'getDraftComment',
        'modified' => 'getModified'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['schema_version'] = isset($data['schema_version']) ? $data['schema_version'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['configuration_id'] = isset($data['configuration_id']) ? $data['configuration_id'] : null;
        $this->container['data'] = isset($data['data']) ? $data['data'] : null;
        $this->container['is_small_data'] = isset($data['is_small_data']) ? $data['is_small_data'] : null;
        $this->container['effective'] = isset($data['effective']) ? $data['effective'] : null;
        $this->container['previous_data'] = isset($data['previous_data']) ? $data['previous_data'] : null;
        $this->container['previous_created'] = isset($data['previous_created']) ? $data['previous_created'] : null;
        $this->container['draft_data'] = isset($data['draft_data']) ? $data['draft_data'] : null;
        $this->container['draft_created'] = isset($data['draft_created']) ? $data['draft_created'] : null;
        $this->container['draft_comment'] = isset($data['draft_comment']) ? $data['draft_comment'] : null;
        $this->container['modified'] = isset($data['modified']) ? $data['modified'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets created
     *
     * @return string
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param string $created created
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets schema_version
     *
     * @return string
     */
    public function getSchemaVersion()
    {
        return $this->container['schema_version'];
    }

    /**
     * Sets schema_version
     *
     * @param string $schema_version schema_version
     *
     * @return $this
     */
    public function setSchemaVersion($schema_version)
    {
        $this->container['schema_version'] = $schema_version;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string $version version
     *
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets configuration_id
     *
     * @return int
     */
    public function getConfigurationId()
    {
        return $this->container['configuration_id'];
    }

    /**
     * Sets configuration_id
     *
     * @param int $configuration_id configuration_id
     *
     * @return $this
     */
    public function setConfigurationId($configuration_id)
    {
        $this->container['configuration_id'] = $configuration_id;

        return $this;
    }

    /**
     * Gets data
     *
     * @return object
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param object $data data
     *
     * @return $this
     */
    public function setData($data)
    {
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets is_small_data
     *
     * @return int
     */
    public function getIsSmallData()
    {
        return $this->container['is_small_data'];
    }

    /**
     * Sets is_small_data
     *
     * @param int $is_small_data is_small_data
     *
     * @return $this
     */
    public function setIsSmallData($is_small_data)
    {
        $this->container['is_small_data'] = $is_small_data;

        return $this;
    }

    /**
     * Gets effective
     *
     * @return string
     */
    public function getEffective()
    {
        return $this->container['effective'];
    }

    /**
     * Sets effective
     *
     * @param string $effective effective
     *
     * @return $this
     */
    public function setEffective($effective)
    {
        $this->container['effective'] = $effective;

        return $this;
    }

    /**
     * Gets previous_data
     *
     * @return string
     */
    public function getPreviousData()
    {
        return $this->container['previous_data'];
    }

    /**
     * Sets previous_data
     *
     * @param string $previous_data previous_data
     *
     * @return $this
     */
    public function setPreviousData($previous_data)
    {
        $this->container['previous_data'] = $previous_data;

        return $this;
    }

    /**
     * Gets previous_created
     *
     * @return string
     */
    public function getPreviousCreated()
    {
        return $this->container['previous_created'];
    }

    /**
     * Sets previous_created
     *
     * @param string $previous_created previous_created
     *
     * @return $this
     */
    public function setPreviousCreated($previous_created)
    {
        $this->container['previous_created'] = $previous_created;

        return $this;
    }

    /**
     * Gets draft_data
     *
     * @return object
     */
    public function getDraftData()
    {
        return $this->container['draft_data'];
    }

    /**
     * Sets draft_data
     *
     * @param object $draft_data draft_data
     *
     * @return $this
     */
    public function setDraftData($draft_data)
    {
        $this->container['draft_data'] = $draft_data;

        return $this;
    }

    /**
     * Gets draft_created
     *
     * @return string
     */
    public function getDraftCreated()
    {
        return $this->container['draft_created'];
    }

    /**
     * Sets draft_created
     *
     * @param string $draft_created draft_created
     *
     * @return $this
     */
    public function setDraftCreated($draft_created)
    {
        $this->container['draft_created'] = $draft_created;

        return $this;
    }

    /**
     * Gets draft_comment
     *
     * @return string
     */
    public function getDraftComment()
    {
        return $this->container['draft_comment'];
    }

    /**
     * Sets draft_comment
     *
     * @param string $draft_comment draft_comment
     *
     * @return $this
     */
    public function setDraftComment($draft_comment)
    {
        $this->container['draft_comment'] = $draft_comment;

        return $this;
    }

    /**
     * Gets modified
     *
     * @return string
     */
    public function getModified()
    {
        return $this->container['modified'];
    }

    /**
     * Sets modified
     *
     * @param string $modified modified
     *
     * @return $this
     */
    public function setModified($modified)
    {
        $this->container['modified'] = $modified;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


